#!/usr/bin/env bash
set -e

extensions_arg=""
repo_arg=""
while [ $# -gt 0 ]; do
  case "$1" in
  --extensions)
    extensions_arg=$2
    shift
    ;;
  --repo)
    repo_arg="$2"
    shift
    ;;
  -h|--help)
    echo "gh lfser --extensions <extensions> --repo <repo>"
    exit 0
    ;;
  esac
  shift
done

# Check if git lfs is installed
if ! [ -x "$(command -v git lfs)" ]; then    
    echo "Git LFS is not installed. Please install Git LFS: https://git-lfs.github.com/."
    exit 1
fi

if [ -z "$extensions_arg" ]; then
  echo "Please provide a list of extensions with the --extensions flag."
  exit 1
fi

echo "Migrating $repo_arg to LFS"
echo "Extensions: $extensions_arg"

if gh repo clone $repo_arg temp; then
    cd temp
    MAIN=`git rev-parse --abbrev-ref HEAD`
    # create all branches locally
    for REF in $(git for-each-ref --format='%(refname)' refs/remotes/origin/ | grep -v ${MAIN} | grep -v HEAD); do
        BRANCH_NAME=${REF#refs/remotes/origin/}
        git branch --track ${BRANCH_NAME} ${REF}
    done
    git lfs migrate import --everything --object-map=lfs-mapping.csv --include="$extensions_arg"
    git reflog expire --expire=now --all
    git gc --prune=now --aggressive
    # push all branches
    for REF in $(git for-each-ref --format='%(refname)' refs/heads); do
        BRANCH_NAME=${REF#refs/heads/}
        git push -f origin ${BRANCH_NAME}
        git lfs push origin ${BRANCH_NAME} --all
    done
    # cleanup
    cd .. ; rm -rf temp
fi
